### ISSUE TITLE
Fix misspelling in path

### ISSUE THREAD

**Issue by coryschires** [illustrativemathematics/pandoc-buildpack#1]
Thanks so much for creating this buildpack! 

I noticed a typo in the compile script: When setting `REAL_DIR`, the word "padoc" should be "pandoc". Specifically, see this line: https://github.com/illustrativemathematics/pandoc-buildpack/blob/master/bin/compile#L28

As a result, I cannot execute pandoc from the command line in the way that you'd expect (i.e. just typing `pandoc`). In case this is causing problems for anyone else, in the meantime you can still use pandoc by pathing directly to the binary:

    /app/vendor/pandoc/bin/pandoc

I thought about making a PR but the change is so small that it seemed silly. Do you think this is something you could fix?

Thanks again for creating this buildpack!

**Comment by econnally** [comment]
hi cory thanks for alerting me. should be fixed here: https://github.com/illustrativemathematics/pandoc-buildpack/commit/0321b5f691a243b312ea39d36bd73bd494bdab2f
