### ISSUE TITLE
Buildpack not compatible with upcoming build system changes

### ISSUE THREAD

**Issue by edmorley** [illustrativemathematics/pandoc-buildpack#6]
Hi! I'm on the team that maintains Heroku's build system.

In the future we plan on changing the value for `$HOME` at build time as part of moving where the build occurs, however scans of frequently used buildpacks have identified this buildpack as not compatible with this upcoming change.

This buildpack currently writes the resolved value of `$HOME` (ie `/app`) into `.profile.d/pandoc.sh` at build time, rather than the actual variable name (`$HOME`):

https://github.com/illustrativemathematics/pandoc-buildpack/blob/d7e607575904ddd030f24a029de188cf3d5998aa/bin/compile#L32
https://github.com/illustrativemathematics/pandoc-buildpack/blob/d7e607575904ddd030f24a029de188cf3d5998aa/bin/compile#L74-L76

In the future, at build time `$HOME` will be another value (for example `/tmp/home`), and no longer match the runtime value of `$HOME` (`/app`).

The fix is to change that line to either escape the dollar sign (so the variable is resolved at runtime):

```
REAL_DIR="\$HOME/vendor/pandoc/bin"
```

Or else just hardcode the `/app` path without using the `$HOME` variable at all:

```
REAL_DIR="/app/vendor/pandoc/bin"
```

Many thanks :-)

**Comment by paul-em** [comment]
Thx for the heads-up, we did not use it anymore. archived the repo.

**Comment by econnally** [comment]
hi @edmorley i'm guessing you mean forks should merge in PR #7 (not issue #1, which is real old). $0.02

**Comment by edmorley** [comment]
Ah indeed - thank you, edited.
